{-
Description:
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
-}

fibonacci :: Int -> Int
fibonacci 0 = 0
fibonacci 1 = 1
fibonacci n =  fibonacci(n - 1) + fibonacci(n - 2)

isEven :: Int -> Bool
isEven n 
   | n `mod` 2 == 0 = True
   | otherwise = False 

main :: IO()
main = putStrLn(show(sum(filter isEven(takeWhile (<4000000) $ map fibonacci [1..]))))